customer/urls.py
from django.urls import path
from customer import views

app_name = "customer"

urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("orders/", views.orders, name="orders"),
    path("order_detail/<order_id>/", views.order_detail, name="order_detail"),
    path("order_item_detail/<order_id>/<item_id>/", views.order_item_detail, name="order_item_detail"),
    path("whislist/", views.wishlist, name="wishlist"),
    path("add_to_wishlist/<id>/", views.add_to_whislist, name="add_to_whislist"),
    path("remove_from_wishlist/<id>/", views.remove_from_wishlist, name="remove_from_wishlist"),
    path("notis/", views.notis, name="notis"),
    path("mark_noti_seen/<id>/", views.mark_noti_seen, name="mark_noti_seen"),
    path("addresses/", views.addresses, name="addresses"),
    path("address_detail/<id>/", views.address_detail, name="address_detail"),
    path("address_create/", views.address_create, name="address_create"),
    path("delete_addresses/<id>/", views.delete_addresses, name="delete_addresses"),
    path("profile/", views.profile, name="profile"),
    path("change_password/", views.change_password, name="change_password"),
]

ecom_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('user/', include('userauths.urls')),
    path('customer/', include('customer.urls')),
    path('vendor/', include('vendor.urls')),
    
    path("ckeditor5/", include("django_ckeditor_5.urls")),
]

handler404 = "store.views.custom_404"

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from store import views

app_name = "store"

urlpatterns = [
    path("", views.index, name="index"), 
    path("detail/<slug>/", views.product_detail, name="product_detail"),
    path("add_to_cart/", views.add_to_cart, name="add_to_cart"),
    path("cart/", views.cart, name="cart"),
    path("delete_cart_item/", views.delete_cart_item, name="delete_cart_item"),
    path("create_order/", views.create_order, name="create_order"),
    path("checkout/<order_id>/", views.checkout, name="checkout"),
    path("coupon_apply/<order_id>/", views.coupon_apply, name="coupon_apply"),
    path("paypal_payment_verify/<order_id>/", views.paypal_payment_verify, name="paypal_payment_verify"),
    path("payment_status/<order_id>/", views.payment_status, name="payment_status"),
    path("stripe_payment/<order_id>/", views.stripe_payment, name="stripe_payment"),
    path("stripe_payment_verify/<order_id>/", views.stripe_payment_verify, name="stripe_payment_verify"),
    path("paystack_payment_verify/<order_id>/", views.paystack_payment_verify, name="paystack_payment_verify"),
    path("flutterwave_payment_callback/<order_id>/", views.flutterwave_payment_callback, name="flutterwave_payment_callback"),

    path('product/<int:product_id>/add_review/', views.add_review, name='add_review'),
    
    path("shop/", views.shop, name="shop"),

    path("search/", views.search_view, name="search"),
    path('about_us/', views.about_us, name='about_us'),
    path("contacto/", views.contacto, name="contacto"),
    
    path("blog/", views.blog, name="blog"),
    path("blog_detail/<slug>/", views.blog_detail, name="blog_detail"),
    
    path("categories/", views.category_list, name="categories"),
    path("category_detail/<slug>/", views.category_detail, name="category_detail"),
    
    path("subscribe/", views.subscribe, name="subscribe"),
    
    path("privacy_policy/", views.polity_policy, name="polity_policy"),
    path("terms_of_service/", views.terms_of_service, name="terms_of_service"),
    
    path("compare/", views.compare_view, name="compare"),
    path("compare/add/<id>/", views.add_to_compare, name="add_to_compare"),
    path("compare/remove/<id>/", views.remove_from_compare, name="remove_from_compare"),
    path('compare/count/', views.get_compare_item_count, name='compare_item_count'),
]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),

    path('access-denied/', views.access_denied, name='access_denied'),
    
    path('forgot-password/', views.forgot_password_view, name='forgot-password'),
    path('reset-password/<uidb64>/<token>/', views.reset_password_view, name='reset-password'),
]

customer/models.py
from django.db import models
from store.models import Product
from userauths.models import User

TYPE = (
    ("New Order", "Nuevo pedido"),
    ("Items shipped", "Artículo enviado"),
    ("Item delivered", "Artículo entregado"),
)

class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="wishlist")
    
    class Meta:
        verbose_name = "Lista de deseos"
    
    def __str__(self):
        if self.product.name:
            return self.product.name
        else :
            return "Lista de deseos"

class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    full_name = models.CharField(max_length=200, null=True, blank=True, default=None)
    mobile = models.CharField(max_length=50, null=True, blank=True, default=None)
    email = models.CharField(max_length=100, null=True, blank=True, default=None)
    country = models.CharField(max_length=100, null=True, blank=True, default=None)
    state = models.CharField(max_length=100, null=True, blank=True, default=None)
    city = models.CharField(max_length=100, null=True, blank=True, default=None)
    address = models.CharField(max_length=100, null=True, blank=True, default=None)
    zip_code = models.CharField(max_length=100, null=True, blank=True, default=None)
    
    class Meta:
        verbose_name = "Dirección de cliente"
    
    def __str__(self):
        return self.full_name
    
class Notifications(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    type = models.CharField(max_length=100, choices=TYPE, default=None)
    seen = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = "Notificación"
        
    def __str__(self):
        return self.type

customer/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib import messages
from django.db import models
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from plugin.paginate_queryset import paginate_queryset
from store import models as store_models
from customer import models as customer_models
from userauths.decorators import customer_required

@login_required
def dashboard(request):
    orders = store_models.Order.objects.filter(customer=request.user)
    total_spent = store_models.Order.objects.filter(customer=request.user).aggregate(total = models.Sum("total"))["total"]
    notis = customer_models.Notifications.objects.filter(user=request.user, seen=False)
    settings = store_models.StoreSettings.objects.first()
    categories = store_models.Category.objects.all()
    context = {
        "orders": orders,
        "total_spent": total_spent,
        "notis": notis,
        "settings": settings,
        "categories": categories,
    }
    return render(request, "customer/dashboard.html", context)

@login_required
def orders(request):
    orders_list = store_models.Order.objects.filter(customer=request.user)
    orders = paginate_queryset(request, orders_list, 10)
    settings = store_models.StoreSettings.objects.first()
    categories = store_models.Category.objects.all()
    context = {
        "orders": orders,
        "orders_list": orders_list,
        "settings": settings,
        "categories": categories,
    }
    return render(request, "customer/orders.html", context)

@login_required
def order_detail(request, order_id):
    order = store_models.Order.objects.get(customer=request.user, order_id=order_id)
    settings = store_models.StoreSettings.objects.first()
    categories = store_models.Category.objects.all()
    context = {
        "order": order,
        "settings": settings,
        "categories": categories,
    }
    return render(request, "customer/order_detail.html", context)

@login_required
def order_item_detail(request, order_id, item_id):
    order = store_models.Order.objects.get(customer=request.user, order_id=order_id)
    item = store_models.OrderItem.objects.get(order=order, item_id=item_id)
    settings = store_models.StoreSettings.objects.first()
    categories = store_models.Category.objects.all()
    context = {
        "order": order,
        "item": item,
        "settings": settings,
        "categories": categories,
    }
    return render(request, "customer/order_item_detail.html", context)

@login_required
def wishlist(request):
    wishlist_list = customer_models.Wishlist.objects.filter(user=request.user)
    wishlist = paginate_queryset(request, wishlist_list, 10)
    settings = store_models.StoreSettings.objects.first()
    categories = store_models.Category.objects.all()
    context = {
        "wishlist_list": wishlist_list,
        "wishlist": wishlist,
        "settings": settings,
        "categories": categories,
    }
    return render(request, "customer/wishlist.html", context)

@login_required
def remove_from_wishlist(request, id):
    wishlist = customer_models.Wishlist.objects.get(user=request.user, id=id)
    wishlist.delete()
    messages.success(request, "Producto eliminado de favoritos")
    return redirect("customer:wishlist")

def add_to_whislist(request, id):
    if request.user.is_authenticated:
        product = store_models.Product.objects.filter(id=id).first()
        wishlist_exists = customer_models.Wishlist.objects.filter(product=product, user=request.user).first()
        if not wishlist_exists:
            customer_models.Wishlist.objects.create(user=request.user, product=product)
        wishlist = customer_models.Wishlist.objects.filter(user=request.user)
        return JsonResponse({"message": "Producto agregado a favoritos", "wishlist_count": wishlist.count()})
    else:
        return JsonResponse({"message": "No estás logueado", "wishlist_count": "0"})
        
@login_required
def notis(request):
    notis_list = customer_models.Notifications.objects.filter(user=request.user, seen=False)
    notis = paginate_queryset(request, notis_list, 10)
    settings = store_models.StoreSettings.objects.first()
    categories = store_models.Category.objects.all()
    context = {
        "notis": notis,
        "notis_list": notis_list,
        "settings": settings,
        "categories": categories,
    }
    return render(request, "customer/notis.html", context)

@login_required
def mark_noti_seen(request, id):
    noti = customer_models.Notifications.objects.get(user=request.user, id=id)
    noti.seen = True
    noti.save()
    messages.success(request, "Notificacion vista")
    return redirect("customer:notis")

@login_required
def addresses(request):
    addresses = customer_models.Address.objects.filter(user=request.user)
    settings = store_models.StoreSettings.objects.first()
    categories = store_models.Category.objects.all()
    context = {
        "addresses": addresses,
        "settings": settings,
        "categories": categories,
    }
    return render(request, "customer/addresses.html", context)

@login_required
def address_detail(request, id):
    address = customer_models.Address.objects.get(user=request.user, id=id)
    settings = store_models.StoreSettings.objects.first()
    categories = store_models.Category.objects.all()
    if request.method == "POST":
        full_name = request.POST.get("full_name")
        mobile = request.POST.get("mobile")
        email = request.POST.get("email")
        country = request.POST.get("country")
        city = request.POST.get("city")
        state = request.POST.get("state")
        address_location = request.POST.get("address")
        zip_code = request.POST.get("zip_code")
        
        address.full_name = full_name
        address.mobile = mobile
        address.email = email
        address.country = country
        address.city = city
        address.state = state
        address.address = address_location
        address.zip_code = zip_code
        address.save()
        
        messages.success(request, "Dirección actualizada")
        return redirect("customer:address_detail", address.id)
    context = {
        "address": address,
        "settings": settings,
        "categories": categories,
    }
    return render(request, "customer/address_detail.html", context)

@login_required
def address_create(request):
    settings = store_models.StoreSettings.objects.first()
    categories = store_models.Category.objects.all()
    if request.method == "POST":
        full_name = request.POST.get("full_name")
        mobile = request.POST.get("mobile")
        email = request.POST.get("email")
        country = request.POST.get("country")
        city = request.POST.get("city")
        state = request.POST.get("state")
        address = request.POST.get("address")
        zip_code = request.POST.get("zip_code")
        
        customer_models.Address.objects.create(
            user=request.user,
            full_name=full_name,
            mobile=mobile,
            email=email,
            country=country,
            city=city,
            state=state,
            address=address,
            zip_code=zip_code,
        )
        messages.success(request, "Dirección creada")
        return redirect("customer:addresses")
    context = {
        "settings": settings,
        "categories": categories,
    }
    return render(request, "customer/address_create.html", context)

@login_required
def delete_addresses(request, id):
    address = customer_models.Address.objects.get(user=request.user, id=id)
    address.delete()
    messages.success(request, "Dirección eliminada")
    return redirect("customer:addresses")

@login_required
def profile(request):
    settings = store_models.StoreSettings.objects.first()
    categories = store_models.Category.objects.all()
    profile = request.user.profile
    if request.method == "POST":
        image = request.FILES.get("image")
        full_name = request.POST.get("full_name")
        mobile = request.POST.get("mobile")
        
        if image != None:
            profile.image = image
            
        profile.full_name = full_name
        profile.mobile = mobile
        
        request.user.save()
        profile.save()
        
        messages.success(request, "Perfil actualizado exitosamente")
        return redirect("customer:profile")
    context = {
        "settings": settings,
        "categories": categories,
        "profile": profile
    }
    return render(request, "customer/profile.html", context)

@login_required
def change_password(request):
    settings = store_models.StoreSettings.objects.first()
    categories = store_models.Category.objects.all()
    if request.method == "POST":
        old_password = request.POST.get("old_password")
        new_password = request.POST.get("new_password")
        confirm_new_password = request.POST.get("confirm_new_password")

        if confirm_new_password != new_password:
            messages.error(request, "La nueva contraseña y confirmar contraseña no coinciden")
            return redirect("customer:change_password")
        if check_password(old_password, request.user.password):
            request.user.set_password(new_password)
            request.user.save()
            messages.success(request, "Contraseña cambiada exitosamente")
            return redirect("customer:profile")
        else :
            messages.error(request, "La contraseña antigua es incorrecta")
            return redirect("customer:change_password")
    context = {
        "settings": settings,
        "categories": categories,
    }
    return render(request, "customer/change_password.html", context)

templates/customer/addresses.html
{% extends 'partials/base.html' %}
{% block title %}Mis direcciones - {{ settings.store_name }}{% endblock %}
{% load humanize %}
{% load static %}
{% block content %}
<main class="main pages">
  <div class="page-header breadcrumb-wrap">
    <div class="container">
      <div class="breadcrumb">
        <a href="/" rel="nofollow"><i class="fi-rs-home mr-5"></i>Inicio</a>
        <span></span> Mis direcciones
      </div>
    </div>
  </div>
  <div class="page-content pt-150 pb-150">
    <div class="container">
      <div class="row">
        <div class="col-lg-10 m-auto">
          <div class="row">
            {% include 'customer/sidebar.html' %}
            <div class="col-md-9">
              <div class="tab-content account orders-content pl-50">
                <div
                  class="tab-pane fade active show"
                  id="orders"
                  role="tabpanel"
                  aria-labelledby="orders-tab"
                >
                  <div class="d-flex justify-content-between mb-4">
                    <h3 class="mb-0">Tus Direcciones</h3>
                    <a href="{% url 'customer:address_create' %}" class="btn btn-primary">Crear dirección <i class="fas fa-plus"></i> </a>
                  </div>

                  <div class="row">
                    
                    {% for address in addresses %}
                      <div class="col-lg-6">
                        <div class="card shadow-sm p-3 mb-3">
                            <div class="card-body">
                            <h5 class="card-title fw-bold">Dirección de envío</h5>
                            <div class="d-flex gap-2 mb-3">
                                <a href="{% url 'customer:address_detail' address.id %}" class="btn btn-sm btn-purple">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a href="{% url 'customer:delete_addresses' address.id %}" class="btn btn-sm btn-danger">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                            <p><strong>Nombres y apellidos:</strong> {{ address.full_name }}</p>
                            <p><strong>Correo electrónico:</strong> {{ address.email }}</p>
                            <p><strong>Número de celular:</strong> {{ address.mobile }}</p>
                            <p><strong>Dirección:</strong> {{ address.address }}</p>
                            <p><strong>Ciudad:</strong> {{ address.city }}</p>
                            <p><strong>Provincia:</strong> {{ address.state }}</p>
                            <p><strong>País:</strong> {{ address.country }}</p>
                            </div>
                        </div>
                      </div>
                    {% endfor %}
                        
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

templates/customer/sidebar.html
<div class="col-md-3">
    <div class="card mb-3">
        <div class="card-body text-center">
            <img src="{{ request.user.profile.image.url }}" alt="Profile" class="rounded-circle img-thumbnail" width="100">
            <h5 class="card-title mt-3">{{ request.user.profile.full_name }}</h5>
            <p class="card-text text-muted">Cliente ID: #{{ request.user.id }}</p>
        </div>
    </div>

    <div class="dashboard-menu">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'dashboard' %}active{% endif %}" href="{% url 'customer:dashboard' %}">
                    <i class="fi-rs-home mr-10"></i>
                    Dashboard
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name in 'orders,order_detail,order_item_detail' %}active{% endif %}" href="{% url 'customer:orders' %}">
                    <i class="fi-rs-shopping-cart mr-10"></i>
                    Pedidos
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'wishlist' %}active{% endif %}" href="{% url 'customer:wishlist' %}">
                    <i class="fi-rs-heart mr-10"></i>
                    Favoritos
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'notis' %}active{% endif %}" href="{% url 'customer:notis' %}">
                    <i class="fi-rs-bell mr-10"></i>
                    Notificaciones
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name in 'addresses,address_detail,address_create,delete_addresses' %}active{% endif %}" href="{% url 'customer:addresses' %}">
                    <i class="fi-rs-marker mr-10"></i>
                    Mis Direcciones
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'profile' %}active{% endif %}" href="{% url 'customer:profile' %}">
                    <i class="fi-rs-user mr-10"></i>
                    Perfil
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'change_password' %}active{% endif %}" href="{% url 'customer:change_password' %}">
                    <i class="fi-rs-lock mr-10"></i>
                    Cambiar contraseña
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'userauths:sign-out' %}">
                    <i class="fi-rs-sign-out mr-10"></i>
                    Cerrar sesión
                </a>
            </li>
        </ul>
    </div>
</div>

templates/customer/wishlist.html
{% extends 'partials/base.html' %}
{% block title %}Favoritos - {{ settings.store_name }}{% endblock %}
{% load humanize %}
{% load static %}

{% block content %}
<main class="main pages">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="/" rel="nofollow"><i class="fi-rs-home mr-5"></i>Inicio</a>
                <span></span> Tus favoritos
            </div>
        </div>
    </div>
    <div class="page-content pt-150 pb-150">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 m-auto">
                    <div class="row">
                        {% include 'customer/sidebar.html' %}
                        <div class="col-md-9">
                            <div class="tab-content account wishlist pl-50">
                                <div class="card">
                                    <div class="card-header">
                                        <h3 class="mb-0">Tus Favoritos ({{ wishlist.paginator.count }})</h3>
                                    </div>
                                </div>
                                <div class="table-responsive shopping-summery">
                                    <table class="table table-wishlist">
                                        <thead>
                                            <tr class="main-heading">
                                                <th class="start pl-30">#</th>
                                                <th scope="col">Producto</th>
                                                <th scope="col">Precio</th>
                                                <th scope="col">Acción</th>
                                                <th scope="col">Quitar</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for w in wishlist %}
                                                <tr class="pt-30">
                                                    <td class="image product-thumbnail pt-40 pl-30">
                                                        <a href="{% url 'store:product_detail' w.product.slug %}">
                                                            <img src="{{ w.product.image.url }}" alt="#">
                                                        </a>
                                                    </td>
                                                    <td class="product-des product-name">
                                                        <h6>
                                                            <a class="product-name mb-10" href="{% url 'store:product_detail' w.product.slug %}">
                                                                {{ w.product.name }}
                                                            </a>
                                                        </h6>
                                                        <p><strong>Categoría: </strong>{{ w.product.category.title }}</p>
                                                        <div class="product-rate-cover">
                                                            <div class="product-rate d-inline-block">
                                                                {% if w.product.average_rating is not None %}
                                                                    <div class="product-rating" style="width: {% widthratio w.product.average_rating 5 100 %}%"></div>
                                                                {% else %}
                                                                    <div class="product-rating" style="width: 0%"></div>
                                                                {% endif %}
                                                            </div>
                                                            <span class="font-small ml-5 text-muted">({{ w.product.average_rating|floatformat:1|default:0 }})</span>
                                                        </div>
                                                    </td>
                                                    <td class="price" data-title="Price">
                                                        <h3 class="text-brand">S/. {{ w.product.price }}</h3>
                                                    </td>
                                                    <td class="text-right" data-title="Cart">
                                                        <input type="hidden" class="quantity" value="1" name="" id="">
                                                        <button type="button" class="btn btn-sm add_to_cart" data-id="{{ w.product.id }}">Agregar al cesto</button>
                                                    </td>
                                                    <td class="action text-center" data-title="Remove">
                                                        <a href="{% url 'customer:remove_from_wishlist' w.id %}" class="text-body"><i class="fi-rs-trash"></i></a>
                                                    </td>
                                                </tr>
                                            {% empty %}
                                                <tr>
                                                    <td colspan="5" class="text-center">Tu lista de deseos está vacía.</td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>

                                <div class="pagination-area mt-20 mb-20">
                                    <nav aria-label="Page navigation example">
                                        <ul class="pagination justify-content-start">

                                            {% if wishlist.has_previous %}
                                                <li class="page-item">
                                                    <a class="page-link" href="?page={{ wishlist.previous_page_number }}">
                                                        <i class="fi-rs-arrow-small-left"></i>
                                                    </a>
                                                </li>
                                            {% endif %}

                                            {% for num in wishlist.paginator.page_range %}
                                                {% if num == wishlist.number %}
                                                    <li class="page-item active">
                                                        <a class="page-link" href="#">{{ num }}</a>
                                                    </li>
                                                {% elif num >= wishlist.number|add:-1 and num <= wishlist.number|add:1 %}
                                                    <li class="page-item">
                                                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                                                    </li>
                                                {% elif num == 1 or num == wishlist.paginator.num_pages %}
                                                    <li class="page-item">
                                                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                                                    </li>
                                                {% elif num == wishlist.number|add:2 %}
                                                    <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                                                {% endif %}
                                            {% endfor %}

                                            {% if wishlist.has_next %}
                                                <li class="page-item">
                                                    <a class="page-link" href="?page={{ wishlist.next_page_number }}">
                                                        <i class="fi-rs-arrow-small-right"></i>
                                                    </a>
                                                </li>
                                            {% endif %}

                                        </ul>
                                    </nav>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}