customer/urls.py
from django.urls import path
from customer import views

app_name = "customer"

urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("orders/", views.orders, name="orders"),
    path("order_detail/<order_id>/", views.order_detail, name="order_detail"),
    path("order_item_detail/<order_id>/<item_id>/", views.order_item_detail, name="order_item_detail"),
    path("whislist/", views.wishlist, name="wishlist"),
    path("add_to_wishlist/<id>/", views.add_to_whislist, name="add_to_whislist"),
    path("remove_from_wishlist/<id>/", views.remove_from_wishlist, name="remove_from_wishlist"),
    path("notis/", views.notis, name="notis"),
    path("mark_noti_seen/<id>/", views.mark_noti_seen, name="mark_noti_seen"),
    path("addresses/", views.addresses, name="addresses"),
    path("address_detail/<id>/", views.address_detail, name="address_detail"),
    path("address_create/", views.address_create, name="address_create"),
    path("delete_addresses/<id>/", views.delete_addresses, name="delete_addresses"),
    path("profile/", views.profile, name="profile"),
    path("change_password/", views.change_password, name="change_password"),
]

ecom_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('user/', include('userauths.urls')),
    path('customer/', include('customer.urls')),
    path('vendor/', include('vendor.urls')),
    
    path("ckeditor5/", include("django_ckeditor_5.urls")),
]

handler404 = "store.views.custom_404"

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from store import views

app_name = "store"

urlpatterns = [
    path("", views.index, name="index"), 
    path("detail/<slug>/", views.product_detail, name="product_detail"),
    path("add_to_cart/", views.add_to_cart, name="add_to_cart"),
    path("cart/", views.cart, name="cart"),
    path("delete_cart_item/", views.delete_cart_item, name="delete_cart_item"),
    path("create_order/", views.create_order, name="create_order"),
    path("checkout/<order_id>/", views.checkout, name="checkout"),
    path("coupon_apply/<order_id>/", views.coupon_apply, name="coupon_apply"),
    path("paypal_payment_verify/<order_id>/", views.paypal_payment_verify, name="paypal_payment_verify"),
    path("payment_status/<order_id>/", views.payment_status, name="payment_status"),
    path("stripe_payment/<order_id>/", views.stripe_payment, name="stripe_payment"),
    path("stripe_payment_verify/<order_id>/", views.stripe_payment_verify, name="stripe_payment_verify"),
    path("paystack_payment_verify/<order_id>/", views.paystack_payment_verify, name="paystack_payment_verify"),
    path("flutterwave_payment_callback/<order_id>/", views.flutterwave_payment_callback, name="flutterwave_payment_callback"),

    path('product/<int:product_id>/add_review/', views.add_review, name='add_review'),
    
    path("shop/", views.shop, name="shop"),

    path("search/", views.search_view, name="search"),
    path('about_us/', views.about_us, name='about_us'),
    path("contacto/", views.contacto, name="contacto"),
    
    path("blog/", views.blog, name="blog"),
    path("blog_detail/<slug>/", views.blog_detail, name="blog_detail"),
    
    path("categories/", views.category_list, name="categories"),
    path("category_detail/<slug>/", views.category_detail, name="category_detail"),
    
    path("subscribe/", views.subscribe, name="subscribe"),
    
    path("privacy_policy/", views.polity_policy, name="polity_policy"),
    path("terms_of_service/", views.terms_of_service, name="terms_of_service"),
    
    path("compare/", views.compare_view, name="compare"),
    path("compare/add/<id>/", views.add_to_compare, name="add_to_compare"),
    path("compare/remove/<id>/", views.remove_from_compare, name="remove_from_compare"),
    path('compare/count/', views.get_compare_item_count, name='compare_item_count'),
]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),

    path('access-denied/', views.access_denied, name='access_denied'),
    
    path('forgot-password/', views.forgot_password_view, name='forgot-password'),
    path('reset-password/<uidb64>/<token>/', views.reset_password_view, name='reset-password'),
]

blog/models.py
from django.db import models

# Create your models here.

store/forms.py
from django import forms
from .models import BlogComment, MensajeContacto

class FormularioContacto(forms.ModelForm):
    class Meta:
        model = MensajeContacto
        fields = ['nombre', 'email', 'telefono', 'asunto', 'mensaje']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo Electrónico'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Teléfono'}),
            'asunto': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Asunto'}),
            'mensaje': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Escribe tu mensaje aquí...', 'rows': 5}),
        }
        
class BlogCommentForm(forms.ModelForm):
    class Meta:
        model = BlogComment
        fields = ["author", "email", "comment"]
        widgets = {
            "author": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre"}),
            "email": forms.EmailInput(attrs={"class": "form-control", "placeholder": "Correo Electrónico"}),
            "comment": forms.Textarea(attrs={"class": "form-control", "placeholder": "Escribe tu comentario...", "rows": 4}),
        }

blog/views.py
from django.shortcuts import render

# Create your views here.

store/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from plugin.service_fee import calculate_service_fee
from store import models as store_models
from django.http import JsonResponse
from decimal import Decimal
from customer import models as customer_models
from vendor import models as vendor_models
from django.db.models import Q, Avg, Sum
from django.contrib import messages
from plugin.tax_calculation import tax_calculation
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from plugin.exchange_rate import convert_usd_inr, convert_usd_to_kobo, convert_usd_to_ngn
from django.core.mail import EmailMultiAlternatives, send_mail
from django.template.loader import render_to_string
from plugin.paginate_queryset import paginate_queryset
from .forms import BlogCommentForm, FormularioContacto
from django.views.decorators.csrf import csrf_exempt
from .models import Subscriber
import requests
import stripe
import random
import json

stripe.api_key = settings.STTRIPE_SECRET_KEY

@csrf_exempt
def subscribe(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            email = data.get("email")

            if not email:
                return JsonResponse({"error": "El correo electrónico es obligatorio."}, status=400)

            subscriber, created = Subscriber.objects.get_or_create(email=email)

            if created:
                return JsonResponse({"message": "¡Te has suscrito correctamente!"}, status=201)
            else:
                return JsonResponse({"message": "¡Este correo ya está suscrito!"}, status=200)

        except json.JSONDecodeError:
            return JsonResponse({"error": "Formato JSON inválido."}, status=400)

    return JsonResponse({"error": "Método de solicitud no permitido."}, status=405)

def search_view(request):
    query = request.GET.get("q", "").strip()  
    category_query = request.GET.get("category", "").strip()
    settings = store_models.StoreSettings.objects.first()
    categories = store_models.Category.objects.all()

    if not query:
        return redirect('store:index')

    products = store_models.Product.objects.filter(status="Published")

    if query:
        products = products.filter(Q(name__icontains=query))

    if category_query:
        products = products.filter(category__id=category_query)

    context = {
        "products": products,
        "query": query,
        "category_query": category_query,
        "settings": settings,
        "categories": categories,
    }
    return render(request, "store/search_results.html", context)
    
def about_us(request):
    about = store_models.AboutUs.objects.first()
    settings = store_models.StoreSettings.objects.first()
    categories = store_models.Category.objects.all()[:15]
    context = {
        "settings": settings,
        "categories": categories,
        "about": about,
    }
    return render(request, 'store/about-us.html', context)

def index(request):
    products = list(store_models.Product.objects.filter(status="Published"))
    random.shuffle(products) 
    products = products[:10]  
    categories = store_models.Category.objects.all()[:15]
    sliders = store_models.Slider.objects.filter(status="Active").order_by("-created_at")
    settings = store_models.StoreSettings.objects.first()

    context = {
        "products": products,
        "categories": categories,
        "sliders": sliders,
        "settings": settings,
    }
    return render(request, "store/index.html", context)

def category_list(request):
    settings = store_models.StoreSettings.objects.first()
    categories_list = store_models.Category.objects.all() 
    categories = paginate_queryset(request, categories_list, 12)
    for category in categories:
        category.product_count = store_models.Product.objects.filter(category=category).count() 
    context = {
        "settings": settings,
        "categories": categories,
        "categories_list": categories_list,
    }
    return render(request, "store/category_list.html", context)

def category_detail(request, slug):
    settings = store_models.StoreSettings.objects.first()
    categories = store_models.Category.objects.all()[:15]
    category = get_object_or_404(store_models.Category, slug=slug)  
    products_list = store_models.Product.objects.filter(category=category)  
    products = paginate_queryset(request, products_list, 15)
    
    context = {
        "category": category,
        "products": products,
        "settings": settings,
        "products_list": products_list,
        "categories": categories,
    }
    return render(request, "store/category_detail.html", context)

def product_detail(request, slug):
    product = store_models.Product.objects.get(status="Published", slug=slug)
    related_products = store_models.Product.objects.filter(category=product.category, status="Published").exclude(id=product.id)[:5]
    settings = store_models.StoreSettings.objects.first()
    categories = store_models.Category.objects.all()[:15]
    product_stock_range = range(1, product.stock + 1)
    context = {
        "product": product,
        "related_products": related_products,
        "product_stock_range": product_stock_range,
        "settings": settings,
        "categories": categories,
        'page_title': f"{product.name} - {settings.store_name}"
    }
    return render(request, "store/product_detail.html", context)

def blog(request):
    settings = store_models.StoreSettings.objects.first()
    categories = store_models.Category.objects.all()[:15]
    posts_list = store_models.BlogPost.objects.filter(status="Published")
    tags = store_models.Tag.objects.all()
    posts = paginate_queryset(request, posts_list, 10)
    context = {
        "settings": settings,
        "categories": categories,
        "posts": posts,
        "posts_list": posts_list,
        "tags": tags,
    }
    return render(request, "store/blog.html", context=context)

def blog_detail(request, slug):
    settings = store_models.StoreSettings.objects.first()
    categories = store_models.Category.objects.all()[:15]
    category_post = store_models.CategoryPost.objects.first()
    post = get_object_or_404(store_models.BlogPost, slug=slug, status="Published")
    comments = post.comments.all().order_by("-created_at")

    tags = post.tags.all() 

    if request.method == "POST":
        form = BlogCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            messages.success(request, "Tu comentario ha sido enviado correctamente.")
            return redirect("store:blog_detail", slug=slug) 
    else:
        form = BlogCommentForm()

    context = {
        "settings": settings,
        "categories": categories,
        "post": post,
        "category_post": category_post,
        "comments": comments,
        "form": form,
        "tags": tags, 
    }
    return render(request, "store/blog_detail.html", context)

def add_to_cart(request):
    id = request.GET.get("id")
    qty = request.GET.get("qty")
    color = request.GET.get("color")
    size = request.GET.get("size")
    cart_id = request.GET.get("cart_id")
    print("color ===", color)
    print("size ===", size)
    request.session['cart_id'] = cart_id
    if not id or not qty or not cart_id:
        return JsonResponse({"error": "No id, qty or cart_id provided."}, status=400)
    
    try:
        product = store_models.Product.objects.get(id=id, status="Published")
    except store_models.Product.DoesNotExist:
        return JsonResponse({"error": "Producto no encontrado."}, status=404)
    
    existing_cart_items = store_models.Cart.objects.filter(cart_id=cart_id, product=product).first()
    
    if int(qty) > product.stock:
        return JsonResponse({"error": "La cantidad supera al stock registrado."}, status=404)

    if not existing_cart_items:
        cart = store_models.Cart()
        cart.product = product
        cart.qty = qty
        cart.price = product.price
        cart.color = color
        cart.size = size
        cart.sub_total = Decimal(product.price) * Decimal(qty)
        cart.shipping = Decimal(product.shipping) * Decimal(qty)
        cart.total = cart.sub_total + cart.shipping
        cart.user = request.user if request.user.is_authenticated else None
        cart.cart_id = cart_id
        cart.save()
        message = "Producto agregado al cesto"
    else :
        existing_cart_items.product = product
        existing_cart_items.qty = qty
        existing_cart_items.price = product.price
        existing_cart_items.color = color
        existing_cart_items.size = size
        existing_cart_items.sub_total = Decimal(product.price) * Decimal(qty)
        existing_cart_items.shipping = Decimal(product.shipping) * Decimal(qty)
        existing_cart_items.total = existing_cart_items.sub_total + existing_cart_items.shipping
        existing_cart_items.user = request.user if request.user.is_authenticated else None
        existing_cart_items.cart_id = cart_id
        existing_cart_items.save()
        message = "Cesto actualizado"
    total_cart_items = store_models.Cart.objects.filter(Q(cart_id=cart_id) | Q(cart_id=cart_id))
    cart_sub_total = store_models.Cart.objects.filter(Q(cart_id=cart_id) | Q(cart_id=cart_id)).aggregate(sub_total=Sum("sub_total"))['sub_total']
    return JsonResponse(
        { 
            "message": message,
            "total_cart_items": total_cart_items.count(),
            "cart_sub_total": "{:,.2f}" . format(cart_sub_total),
            "item_sub_total": "{:,.2f}" . format(existing_cart_items.sub_total) if existing_cart_items else "{:,.2f}" . format(cart.sub_total)
        },
    )
    
def cart(request):
    if "cart_id" in request.session:

templates/store/category_detail.html
{% extends 'partials/base.html' %}
{% block title %}{{ category.title }} - Categoría de {{ settings.store_name }}{% endblock %}
{% load humanize %}
{% load static %}

{% block content %} 
<style>
    .una-linea {
        display: inline-block; /* Asegura que funcione correctamente */
        max-width: 100%; /* Ajusta al ancho del contenedor */
        white-space: nowrap; /* Evita que el texto se divida en varias líneas */
        overflow: hidden; /* Oculta el texto que se desborda */
        text-overflow: ellipsis; /* Muestra "..." si el texto es muy largo */
    }
</style>
<main class="main">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="{% url 'store:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Inicio</a>
                <span></span> <a href="{% url 'store:categories' %}">Categorías</a> <span></span> {{ category.title }}
            </div>
        </div>
    </div>
    <div class="container mb-30">
        <div class="archive-header-2 text-center pt-80 pb-50">
            <h1 class="display-2 mb-50">{{ category.title }}</h1>
        </div>
        <div class="row flex-row-reverse">
            <div class="col-lg-4-5">
                <div class="shop-product-fillter">
                    <div class="totall-product">
                        <p>Tenemos <strong class="text-brand">{{ products_list.count }}</strong> productos para ti!</p>
                    </div>
                </div>
                <div class="row product-grid">
                    {% for p in products %}
                        <div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
                            <div class="product-cart-wrap mb-30">
                                <div class="product-img-action-wrap">
                                    <div class="product-img product-img-zoom">
                                        <a href="{% url 'store:product_detail' p.slug %}">
                                            <img class="default-img" style="width: 180px; height: 180px; object-fit: contain;" src="{{p.image.url}}" alt="" />
                                        </a>
                                    </div>
                                    <div class="product-action-1">
                                        <a aria-label="Agregar a favoritos" class="action-btn add_to_wishlist" data-product_id="{{p.id}}" href="javascript:void(0);">
                                            <i class="fi-rs-heart"></i>
                                        </a>
                                        <a aria-label="Comparar"
                                            class="action-btn add_to_compare"
                                            href="javascript:void(0);"
                                            data-product_id="{{ p.id }}">
                                            <i class="fi-rs-shuffle"></i>
                                        </a>
                                    </div>
                                    {% if p.get_discount_percent > 0 %}
                                        <div class="product-badges product-badges-position product-badges-mrg">
                                            <span class="new">- {{ p.get_discount_percent|floatformat:"0" }}%</span>
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="product-content-wrap">
                                    <div class="product-category">
                                        <a href="{% url 'store:category_detail' p.category.slug %}">{{p.category.title}}</a>
                                    </div>
                                    <h2><a href="{% url 'store:product_detail' p.slug %}" class="una-linea">{{p.name}}</a></h2>
                                    <div class="product-rate-cover">
                                        <div class="product-rate d-inline-block">
                                            {% if p.average_rating is not None %}
                                                <div class="product-rating" style="width: {% widthratio p.average_rating 5 100 %}%"></div>
                                            {% else %}
                                                <div class="product-rating" style="width: 0%"></div>
                                            {% endif %}
                                        </div>
                                        <span class="font-small ml-5 text-muted"> ({{ p.average_rating|floatformat:1|default:0 }})</span>
                                    </div>
                                    <div class="product-card-bottom">
                                        <div class="product-price">
                                            <span>S/. {{p.price}}</span> <br>
                                            <span class="old-price"></span>
                                            {% if p.regular_price %}
                                                <span class="old-price">S/. {{p.regular_price}}</span>
                                            {% endif %}
                                        </div>
                                        <div class="add-cart">
                                            <a class="add add_to_cart" href="javascript:void(0);" data-id="{{ p.id }}">
                                                <i class="fi-rs-shopping-cart mr-5"></i>Cesto 
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="pagination-area mt-20 mb-20">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-start">
                            {% if products.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ products.previous_page_number }}">
                                        <i class="fi-rs-arrow-small-left"></i>
                                    </a>
                                </li>
                            {% endif %}

                            {% for num in products.paginator.page_range %}
                                {% if num == products.number %}
                                    <li class="page-item active">
                                        <a class="page-link" href="#">{{ num }}</a>
                                    </li>
                                {% elif num >= products.number|add:-1 and num <= products.number|add:1 %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                                    </li>
                                {% elif num == 1 or num == products.paginator.num_pages %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                                    </li>
                                {% elif num == products.number|add:2 %}
                                    <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                                {% endif %}
                            {% endfor %}

                            {% if products.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ products.next_page_number }}">
                                        <i class="fi-rs-arrow-small-right"></i>
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="col-lg-1-5 primary-sidebar sticky-sidebar">
                <div class="sidebar-widget widget-store-info mb-30 bg-3 border-0">
                    <div class="vendor-logo mb-30">
                        <img src="{{category.image.url}}" style="width: 136px; height: 150px; object-fit: contain;" alt="" />
                    </div>
                    <div class="vendor-info">
                        <h4 class="mb-5"><a href="{% url 'store:category_detail' category.slug %}" class="text-heading">{{category.title}}</a></h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

templates/store/contacto.html
{% extends 'partials/base.html' %}
{% block title %}Contacto - {{ settings.store_name }}{% endblock %}
{% load static %}

{% block content %}
<main class="main pages">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="{% url 'store:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>inicio</a>
                <span></span>Contacto
            </div>
        </div>
    </div>
    <div class="page-content pt-50">

        <div class="container">
            <div class="row">
                <div class="col-xl-10 col-lg-12 m-auto">
                    <section class="mb-50">
                        <div class="row">
                            <div class="col-xl-8">
                                <div class="contact-from-area padding-20-row-col">
                                    <h5 class="text-brand mb-10">Formualario de contacto</h5>
                                    <h2 class="mb-10">Envíanos un mensaje</h2>
                                    <p class="text-muted mb-30 font-sm">Tu dirección de correo no será publicada. Los campos obligatorios están marcados con *</p>
                                    <form class="contact-form-style mt-30" id="contact-form" action="{% url 'store:contacto' %}" method="post">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-lg-6 col-md-6">
                                                <div class="input-style mb-20">
                                                    {{ form.nombre }}
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6">
                                                <div class="input-style mb-20">
                                                    {{ form.email }}
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6">
                                                <div class="input-style mb-20">
                                                    {{ form.telefono }}
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6">
                                                <div class="input-style mb-20">
                                                    {{ form.asunto }}
                                                </div>
                                            </div>
                                            <div class="col-lg-12 col-md-12">
                                                <div class="textarea-style mb-30">
                                                    {{ form.mensaje }}
                                                </div>
                                                <button class="submit submit-auto-width" type="submit">Enviar mensaje</button>
                                            </div>
                                        </div>
                                    </form>
                                    <p class="form-messege"></p>
                                </div>
                            </div>
                            <div class="col-lg-4 pl-50 d-lg-block d-none">
                                <img class="border-radius-15 mt-50" src="{% static 'assets/imgs/page/contact-2.png' %}" alt="Contact Image" />
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/store/payment_status.html
{% extends 'partials/base.html' %}
{% block title %}Esatado de pago - {{ settings.store_name }}{% endblock %}
{% load humanize %}
{% load static %}

{% block content %} 
<main class="main">
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                
                {% if payment_status == "paid" %}
                    <div class="card shadow-sm">
                        <div class="card-body text-center p-5">
                            <i class="fas fa-check-circle fa-4x text-success mb-4"></i>
                            <h2 class="card-title mb-3">¡Pedido Completado! </h2>
                            <p class="card-text text-muted mb-4">
                                Gracias por tu compra. Tu pedido ha sido procesado con éxito.
                            </p>  
                            <p class="card-text text-muted mb-4">
                                Su pedido <span style="color: green;" class="fw-bold">#{{order.order_id}}</span> ha sido completado. <br>
                                Hemos enviado los detalles del pedido a su correo electrónico.
                            </p>
                            <a href="{% url 'customer:orders' %}" class="btn btn-primary">
                                <i class="fa-solid fa-cart-shopping"></i> Ver pedidos
                            </a>
                        </div>
                    </div>
                {% endif %}

                {% if payment_status == "failed" %}
                    <div class="card shadow-sm">
                        <div class="card-body text-center p-5">
                            <i class="fas fa-xmark-circle fa-4x text-danger mb-4"></i>
                            <h2 class="card-title mb-3">¡Pedido no completado! </h2>
                            <a href="{% url 'store:checkout' order.order_id %}" class="btn btn-primary">
                                <i class="fa-solid fa-refresh"></i> Volver a intentar
                            </a>
                        </div>
                    </div>
                {% endif %}
                    
            </div>
        </div>
    </div>
</main>
{% endblock content %}